---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-deployment
  template:
    metadata:
      labels:
        app: my-app-deployment
    spec:
      containers:
        - name: my-app-deployment
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
               cpu: "0.5m"
               memory: "500M"
            limits:
              cpu: "1m"            
              memory: "1Gi"
