---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-deployment
  template:
    metadata:
      labels:
        app: my-app-deployment
    spec:
      containers:
        - name: my-app-deployment
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-storage
              mountPath: /mnt/data
      volumes:
        - name: my-storage
          persistentVolumeClaim:
            claimName: my-pvc
